
export var facetJSON = [
  {"name": "Brand",
    "categorynames": ['Acer', 'Alienware', 'Apple', 'Dell', 'Google', 'HP', 'LG', 'Lenovo', 'MSI', 'Microsoft', 'Razer', 'Samsung'],
    "categorycounts": [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
    "type": "categorical",
    "borders": [],
    "values": ['acer', 'alienware', 'apple', 'dell', 'google', 'hp', 'lg', 'lenovo', 'msi', 'microsoft', 'razer', 'samsung', 'other'],
    "fieldname": "brand_filter",
    "activecategories": [false, false, false, false, false, false, false, false, false, false, false, false],
    "mapping": [[], [0,1,3,4,5,6,7,8,10], [2,9,11]],
    "mappingnames": ["low reputation","reputable","high reputation"]},

  {"name": "Price",
    "categorynames": ["under 200£", "200£ - 399£", "400£ - 599£", "600£ - 799£", "800£ - 999£", "1000£ - 1399£", "1400£ - 1999£", "over 2000£"],
    "categorycounts": [-1, -1, -1, -1, -1, -1, -1, -1],
    "type": "interval",
    "borders": [[0, 200], [200, 400], [400, 600], [600, 800], [800, 1000], [1000, 1400], [1400, 2000], [2000, 100000]],
    "values": [],
    "fieldname": "price_filter",
    "activecategories": [false, false, false, false, false, false, false, false],
    "mapping": [[0,1], [2,3], [4,5,6,7]],
    "mappingnames": ["cheap","average","expensive"]},

  {"name": "Screen Size",
    "categorynames": ["under 12in", "12in - 13.9in", "14in - 15.9in", "16in - 17.9in", "over 18in"],
    "categorycounts": [-1, -1, -1, -1, -1],
    "type": "interval",
    "borders": [[0.0,12.0], [12.0, 14.0], [14.0,16.0], [16.0, 18.0], [18.0, 30.0]],
    "values": [],
    "fieldname": "screenSize_filter",
    "activecategories": [false, false, false, false, false],
    "mapping": [[0], [1,2,3], [4]],
    "mappingnames": ["small","medium","large"]},

  {"name": "Storage Size",
    "categorynames": ["under 255GB", "256GB - 499GB", "500GB - 999GB", "1TB", "over 1TB"],
    "categorycounts": [-1, -1, -1, -1, -1],
    "type": "interval",
    "borders": [[0, 256], [256, 500], [500, 1000], [1000, 1001], [1001, 100000]],
    "values": [],
    "fieldname": "totalStorageCapacity_filter",
    "activecategories": [false, false, false, false, false],
    "mapping": [[0,1], [2,3], [4]],
    "mappingnames": ["small","medium","large"]},

  {"name": "RAM Size",
    "categorynames": ["under 4GB", "6GB", "8GB", "12GB", "16GB", "over 16GB"],
    "categorycounts": [-1, -1, -1, -1, -1, -1],
    "type": "interval",
    "borders": [[0, 4], [6,8], [8, 12], [12,16], [16,17], [17, 500]],
    "values": [],
    "fieldname": "systemMemoryRam_filter",
    "activecategories": [false, false, false, false, false, false],
    "mapping": [[0,1], [2,3,4], [5]],
    "mappingnames": ["small","medium","large"]},

  {"name": "Weight",
    "categorynames": ["under 2 pounds", "2 - 3 pounds", "3 - 4 pounds", "4 - 5 pounds", "5 - 6 pounds", "6 - 7 pounds", "over 7 pounds"],
    "categorycounts": [-1, -1, -1, -1, -1, -1, -1],
    "type": "interval",
    "borders": [[0.0, 2.0], [2.0, 3.0], [3.0, 4.0], [4.0, 5.0], [5.0, 6.0], [6.0, 7.0], [7.0, 100.0]],
    "values": [],
    "fieldname": "productWeight_filter",
    "activecategories": [false, false, false, false, false, false, false],
    "mapping": [[0,1],[2,3,4,5],[6]],
    "mappingnames": ["light","medium","heavy"]},

  {"name": "Battery Life",
    "categorynames": ["under 5h", "5h-10h", "11h-15h", "over 15h"],
    "categorycounts": [-1, -1, -1, -1],
    "type": "interval",
    "borders": [[0.0, 5.0], [5.0, 11.0], [11.0, 16.0], [16.0, 100.0]],
    "values": [],
    "fieldname": "batteryLife_filter",
    "activecategories": [false, false, false, false],
    "mapping": [[0], [1], [2,3]],
    "mappingnames": ["short","medium","long"]},

];


export var facetJSONvague = [

 {"name": "Brand",
    "categorynames": ["low reputation","reputable: Acer, Alienware, Dell, Google, HP, LG, Lenovo, MSI, Razer","high reputation: Apple, Microsoft, Samsung"],
    "categorycounts": [-1, -1, -1],
    "type": "categorical",
    "borders": [],
    "values": ['low','medium','high'],
    "fieldname": "brand_vagueFront",
    "activecategories": [false, false, false],
    "mapping": [[], [0,1,3,4,5,6,7,8,10], [2,9,11]],
    "mappingnames": ["low reputation","reputable","high reputation"]},

  {"name": "Price",
    "categorynames": ['cheap: under 400£','medium: 400£-800£','expensive: over 800£'],
    "categorycounts": [-1, -1, -1],
    "type": "categorical",
    "borders": [],
    "values": ['cheap','medium','expensive'],
    "fieldname": "price_vagueFront",
    "activecategories": [false, false, false],
    "mapping": [[0,1], [2,3], [4,5,6,7]],
    "mappingnames": ["cheap","average","expensive"]},

  {"name": "Screen Size",
    "categorynames": ['small: under 12in','medium: 12in-18in','large: over 18in'],
    "categorycounts": [-1, -1, -1],
    "type": "categorical",
    "borders": [],
    "values": ['small','medium','large'],
    "fieldname": "screenSize_vagueFront",
    "activecategories": [false, false, false],
    "mapping": [[0], [1,2,3], [4]],
    "mappingnames": ["small","medium","large"]},

  {"name": "Storage Size",
    "categorynames": ['small: under 500GB','medium: 500GB-1024GB','large: over 1024GB'],
    "categorycounts": [-1, -1, -1],
    "type": "categorical",
    "borders": [],
    "values": ['small','medium','large'],
    "fieldname": "totalStorageCapacity_vagueFront",
    "activecategories": [false, false, false],
    "mapping": [[0,1], [2,3], [4]],
    "mappingnames": ["small","medium","large"]},

  {"name": "RAM Size",
    "categorynames": ['small: under 8GB','medium: 8GB-16GB','large: over 16GB'],
    "categorycounts": [-1, -1, -1],
    "type": "categorical",
    "borders": [],
    "values": ['small','medium','large'],
    "fieldname": "systemMemoryRam_vagueFront",
    "activecategories": [false, false, false],
    "mapping": [[0,1], [2,3,4], [5]],
    "mappingnames": ["small","medium","large"]},

  {"name": "Weight",
    "categorynames": ['light: under 3 pounds','medium: 3 - 7 pounds','heavy: over 7 pounds'],
    "categorycounts": [-1, -1, -1],
    "type": "categorical",
    "borders": [],
    "values": ['light','medium','heavy'],
    "fieldname": "productWeight_vagueFront",
    "activecategories": [false, false, false],
    "mapping": [[0,1],[2,3,4,5],[6]],
    "mappingnames": ["light","medium","heavy"]},

  {"name": "Battery Life",
    "categorynames": ['short: under 5h','medium: 5h-10h','long: over 11h'],
    "categorycounts": [-1, -1, -1],
    "type": "categorical",
    "borders": [],
    "values": ['short','medium','long'],
    "fieldname": "batteryLife_vagueFront",
    "activecategories": [false, false, false],
    "mapping": [[0], [1], [2,3]],
    "mappingnames": ["short","medium","long"]},

];
